language: rust
rust: stable
os:
  - linux
  - osx
sudo: false
cache: cargo

script:
  - travis_wait 60 cargo build # Blocks crate takes a while to compile - but it should be cached after the first run
  - travis_wait 60 cargo test