language: rust
rust: stable
os:
  - linux
sudo: required
cache: cargo

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-C link-dead-code"
    - CARGO_MAKE_RUN_CODECOV="true"

script:
  - cargo install --debug cargo-make
  - travis_wait 90 cargo make workspace-ci-flow --no-workspace