language: rust
rust: stable
os:
  - linux
sudo: required
cache: cargo

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-C link-dead-code"
    - CODECOV_TOKEN="6ba7ddc6-ae93-413b-a7cd-d66c80f9028c"

script:
  - cargo install --debug --force cargo-make
  - travis_wait 90 cargo build
  - travis_wait 90 cargo test
  - sudo /home/travis/.cargo/bin/cargo make --no-workspace workspace-coverage