[workspace]
members = [
    "api",
    "server",
    "core",
    "core/anvil",
    "core/blocks",
    "core/blocks/generator",
    "core/biomes",
    "core/chunk",
    "core/chunk_map",
    "core/entity_metadata",
    "core/item_block",
    "core/items",
    "core/inventory",
    "core/network",
    "core/util",
    "codegen",
    "generator",
    "data",
    "data/macro"
]
