[package]
name = "feather-server-template"
version = "0.5.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
feather-core = { path = "../../core" }
feather-server-types = { path = "../types" }
feather-server-util = { path = "../util" }

fecs = { path = "/home/caelum/dev/fecs" }
