[package]
name = "feather-server-chunk"
version = "0.5.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
feather-core = { path = "../../core" }
feather-server-types = { path = "../types" }
feather-server-util = { path = "../util" }
feather-server-worldgen = { path = "../worldgen" }

fecs = { git = "https://github.com/feather-rs/fecs", rev = "1dae7a1870209a8af0326e3b6e18dff9e1a2f67e" }
parking_lot = "0.10"
ahash = "0.3"
rayon = "1.3"
crossbeam = "0.7"
log = "0.4"
smallvec = "1.4"
anyhow = "1.0"
