[io]
# Packets with a size more than or equal to this value will be sent compressed.
# Compressing packets reduces bandwidth usage but increases CPU activity.
compression-threshold = 256
# The number of worker threads used for asynchronous IO.
# Set to the number of cores on your CPU for optimal performance.
io-worker-threads = 8

[proxy]
# IP forwarding using either "bungee" (BungeeCord/Waterfall/Travertine) or "velocity" (Velocity)
proxy-mode = "none"

[server]
online-mode = true
motd = "&lMesa called Jar Jar Binks!\n           Mesa your humble servant!"
max-players = 16
default-gamemode = "survival"
difficulty = "normal"
view-distance = 6
address = "127.0.0.1"
port = 25565

[gameplay]
monster-spawning = true
animal-spawning = true
pvp = true
nerf-spawner-mobs = false
# Either "1.8" or "1.9"
pvp-style = "1.8"

[log]
level = "trace"