[package]
name = "feather_server"
version = "0.1.0"
authors = ["caelunshun <caelum12321@gmail.com>"]
edition = "2018"

[dependencies]
feather_core = { path = "../core" }
mio = "0.6.19"
mio-extras = "2.0.5"
crossbeam = "0.7.1"
log = "0.4.6"
simple_logger = "1.3.0"
uuid = "0.7.4"
derive-new = "0.5.6"
serde = "1.0.92"
serde_derive = "1.0.92"
serde_json = "1.0.39"
toml = "0.5.1"
openssl = "0.10.23"
rand = "0.7.0-pre.1"
bytes = "0.4.12"

[dev-dependencies]
mockers = "0.20.0"
mockers_derive = "0.20.0"
