[package]
name = "feather_server"
version = "0.1.0"
authors = ["caelunshun <caelum12321@gmail.com>"]
edition = "2018"

[dependencies]
feather_core = { path = "../core" }
mio = "0.6.19"
mio-extras = "2.0.5"
crossbeam = "0.7.1"
log = "0.4.6"
simple_logger = "1.3.0"
uuid = "0.7.4"