[package]
name = "feather-inventory"
version = "0.6.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
feather-items = { path = "../items" }
smallvec = "1.3"
once_cell = "1.3"
