[package]
name = "feather-server-packet-buffer"
version = "0.5.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
feather-core = { path = "../../core" }

fecs = { git = "https://github.com/feather-rs/fecs", rev = "1dae7a1870209a8af0326e3b6e18dff9e1a2f67e" }
smallvec = "1.4"
parking_lot = "0.10"
strum = "0.18"
num-traits = "0.2"
ahash = "0.3"
once_cell = "1.3"
indexmap = "1.3"
crossbeam = "0.7"
