[package]
name = "feather-server-packet-buffer"
version = "0.5.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
feather-core = { path = "../../core" }

fecs = { git = "https://github.com/feather-rs/fecs", rev = "fed8bcb516941b12cb980e354e77b699be075a89" }
smallvec = "1.4"
parking_lot = "0.10"
strum = "0.18"
num-traits = "0.2"
ahash = "0.3"
once_cell = "1.3"
indexmap = "1.3"
crossbeam = "0.7"
