[package]
name = "feather-loot"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
hashbrown = "0.7"
uuid = "0.8"
