[package]
name = "feather-server-util"
version = "0.5.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
feather-core = { path = "../../core" }
feather-server-types = { path = "../types" }

fecs = { path = "/home/caelum/dev/fecs" }
nalgebra-glm = "0.6"
arrayvec = "0.5"
smallvec = "1.4"
rand = "0.7"
rand_distr = "0.2"
itertools = "0.9"
futures = "0.3"
tokio = { version = "0.2", features = ["full"] }
ahash = "0.3"
inventory = "0.1"
anyhow = "1.0"
