[package]
name = "fapi"
version = "0.1.0"
authors = ["caelunshun <caelum12321@gmail.com>"]
edition = "2018"

[dependencies]
fapi-common = { path = "common" }
fapi-macros = { path = "macros" }

serde_json = "1.0"
bstr = "0.2"
log = "0.4"
